"""Emit the paper's RQ1 table with our computed numbers substituted in.

The table body reproduces the supervisor's template exactly -- same column
spec, rules, row order, section bands, and macros -- so the generated file is
a drop-in replacement for the block in the paper source. Only the numbers
change.

Cells we have verified results for are filled from the RQ1 run. Any cell we
have not computed keeps whatever the template already carried, and every such
cell is listed in ``provenance.md`` so no inherited number is mistaken for a
freshly measured one.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import pandas as pd

_ROOT = Path(__file__).resolve().parents[2]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

DATASETS = ("BigCloneBench", "AtCoder")
METRICS = ("P", "R", "F1", "Acc")

# (LaTeX label, key in our results CSV). ``None`` marks a structural line.
LAYOUT: tuple[tuple[str, str | None], ...] = (
    ("\\textbf{\\method{}}", "SPECTRA-Siam"),
    ("MIDRULE", None),
    ("SECTION:Learned latent spectral representation", None),
    ("\\method{} Spectrum + No Train", "SPECTRA-Siam Spectrum + No Train"),
    ("\\method{} Spectrum + RF", "SPECTRA-Siam Spectrum + RF"),
    ("\\method{} Spectrum + LR", "SPECTRA-Siam Spectrum + LR"),
    ("\\method{} Spectrum + SNN", "SPECTRA-Siam Spectrum + SNN"),
    ("MIDRULE", None),
    ("SECTION:Fixed-graph spectral representations", None),
    ("AST + No Train", "AST + No Train"),
    ("AST + RF", "AST + RF"),
    ("AST + LR", "AST + LR"),
    ("AST + SNN", "AST + SNN"),
    ("MIDRULE", None),
    ("CFG + No Train", "CFG + No Train"),
    ("CFG + RF", "CFG + RF"),
    ("CFG + LR", "CFG + LR"),
    ("CFG + SNN", "CFG + SNN"),
    ("MIDRULE", None),
    ("DDG + No Train", "DDG + No Train"),
    ("DDG + RF", "DDG + RF"),
    ("DDG + LR", "DDG + LR"),
    ("DDG + SNN", "DDG + SNN"),
    ("MIDRULE", None),
    ("CPG + No Train", "CPG + No Train"),
    ("CPG + RF", "CPG + RF"),
    ("CPG + LR", "CPG + LR"),
    ("CPG + SNN", "CPG + SNN"),
    ("MIDRULE", None),
    ("\\textbf{Predict All Clone}", "Predict All Clone"),
)

CAPTION = (
    "Performance of \\method{} and spectral representations on BigCloneBench and "
    "AtCoder. Fixed-graph rows use spectra derived from conventional program graphs, "
    "while the latent-spectrum rows use the learned spectral representation of "
    "\\method{} without its original MLP prediction head. P, R, F1, and Acc.\\ denote "
    "precision, recall, F1-score, and accuracy, respectively."
)


def format_value(value: float | None) -> str | None:
    """Two decimals, leading zero stripped, matching the paper's style."""
    if value is None or pd.isna(value):
        return None
    text = f"{float(value):.2f}"
    return text if text.startswith("1") else text.lstrip("0")


def load_measured(results_csv: Path | None) -> dict[str, dict[str, float]]:
    if results_csv is None or not results_csv.is_file():
        return {}
    frame = pd.read_csv(results_csv).drop_duplicates(subset=["Method"], keep="last")
    return {
        str(row.Method): {metric: getattr(row, metric) for metric in METRICS}
        for row in frame.itertuples()
    }


def parse_template_numbers(template: Path) -> dict[str, dict[str, list[str]]]:
    """Recover the numbers already present in the paper's RQ1 table.

    Used only as a fallback for cells we have not measured, so an unfinished
    sweep still produces a compilable table instead of blanks.
    """
    text = template.read_text(encoding="utf-8", errors="ignore")
    match = re.search(r"\\label\{tab:rq1\}(.*?)\\end\{table\}", text, re.S)
    if not match:
        return {}
    body = match.group(1)
    values: dict[str, dict[str, list[str]]] = {}
    # Each data row is "<label>\n& a & b & c & d\n& e & f & g & h \\"
    pattern = re.compile(
        r"^(?P<label>[^\n&%\\][^\n&]*|\\textbf\{[^\n]*?\}|\\method\{\}[^\n&]*)\n"
        r"&\s*(?P<bcb>[^\n]+?)\n&\s*(?P<at>[^\n]+?)\s*\\\\",
        re.M,
    )
    for row in pattern.finditer(body):
        label = row.group("label").strip()
        bcb = [cell.strip() for cell in row.group("bcb").split("&")]
        atc = [cell.strip() for cell in row.group("at").split("&")]
        if len(bcb) == 4 and len(atc) == 4:
            values[label] = {"BigCloneBench": bcb, "AtCoder": atc}
    return values


def build_table(
    measured: dict[str, dict[str, dict[str, float]]],
    fallback: dict[str, dict[str, list[str]]],
) -> tuple[str, list[str]]:
    lines = [
        "% Generated by research/rq1/build_latex.py -- structure matches the paper template.",
        "\\begin{table}[!htbp]",
        "\\centering",
        f"\\caption{{{CAPTION}}}",
        "\\label{tab:rq1}",
        "",
        "\\scriptsize",
        "\\setlength{\\tabcolsep}{2.4pt}",
        "\\renewcommand{\\arraystretch}{1.00}",
        "",
        "\\begin{tabular}{@{}lcccccccc@{}}",
        "\\toprule",
        "& \\multicolumn{4}{c}{\\textbf{BigCloneBench}}",
        "& \\multicolumn{4}{c}{\\textbf{AtCoder}} \\\\",
        "\\cmidrule(lr){2-5}",
        "\\cmidrule(l){6-9}",
        "\\textbf{Method}",
        "& \\textbf{P} & \\textbf{R} & \\textbf{F1} & \\textbf{Acc.}",
        "& \\textbf{P} & \\textbf{R} & \\textbf{F1} & \\textbf{Acc.} \\\\",
        "\\midrule",
        "",
    ]
    inherited: list[str] = []
    for label, key in LAYOUT:
        if label == "MIDRULE":
            lines += ["\\midrule", ""]
            continue
        if label.startswith("SECTION:"):
            lines += [
                "\\rowcolor{black!7}",
                f"\\multicolumn{{9}}{{@{{}}l}}{{\\textit{{{label.split(':', 1)[1]}}}}} \\\\",
                "",
            ]
            continue
        cells: dict[str, list[str]] = {}
        for dataset in DATASETS:
            row = measured.get(dataset, {}).get(key or "", {})
            rendered = [format_value(row.get(metric)) for metric in METRICS]
            if all(value is not None for value in rendered):
                cells[dataset] = rendered  # type: ignore[assignment]
            else:
                previous = fallback.get(label, {}).get(dataset)
                cells[dataset] = previous if previous else [".xx"] * 4
                inherited.append(f"{label} / {dataset}")
        lines += [
            label,
            "& " + " & ".join(cells["BigCloneBench"]),
            "& " + " & ".join(cells["AtCoder"]) + " \\\\",
            "",
        ]
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n", inherited


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--atcoder-results", type=Path,
                        default=_ROOT.parent / "outputs/kaggle/RQ1/table_results/atcoder/rq1_table_rows.csv")
    parser.add_argument("--xglue-results", type=Path,
                        default=_ROOT.parent / "outputs/kaggle/RQ1/table_results/xglue/rq1_table_rows.csv")
    parser.add_argument("--template", type=Path, default=_ROOT / "kaggle" / "lecture.txt")
    parser.add_argument("--output-dir", type=Path, default=_ROOT / "kaggle" / "latex" / "rq1")
    args = parser.parse_args()

    measured = {
        "AtCoder": load_measured(args.atcoder_results),
        "BigCloneBench": load_measured(args.xglue_results),
    }
    for dataset, rows in measured.items():
        print(f"{dataset:15s}: {len(rows)} measured rows")

    fallback = parse_template_numbers(args.template)
    print(f"template rows recovered for fallback: {len(fallback)}")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    table, inherited = build_table(measured, fallback)
    (args.output_dir / "table_rq1.tex").write_text(table, encoding="utf-8")

    report = ["# RQ1 table provenance", ""]
    total = sum(len(rows) for rows in measured.values())
    report += [f"Measured cells written from our runs: {total} rows across both datasets.", ""]
    if inherited:
        report += [
            "## Cells NOT measured by us (kept from the existing paper table)",
            "",
            "These were not produced by the finished RQ1 runs in this repository, so they",
            "carry over from the template unchanged. Re-run the RQ1 table for that dataset",
            "to replace them with measured values.",
            "",
            *(f"- {item}" for item in inherited),
        ]
    else:
        report.append("Every cell in the table comes from a measured run.")
    (args.output_dir / "provenance.md").write_text("\n".join(report) + "\n", encoding="utf-8")

    print(f"\nwrote {args.output_dir/'table_rq1.tex'}")
    print(f"wrote {args.output_dir/'provenance.md'}")
    print(f"cells kept from the template (not measured here): {len(inherited)}")


if __name__ == "__main__":
    main()
